// This file is generated by the create-files script in ../utils.
// Day 12 part 1
// https://adventofcode.com/2021/day/12
// input: day12/input.txt

const d12p1Input = (await Deno.readTextFile('day12/input.txt'))
  .split('\n')
  .filter((l) => !!l);

const caveMap = d12p1Input.map((l) => {
  const [pathStart, pathEnd] = l.split('-');
});
