// This file is generated by the create-files script in ../utils.
// Day 9 part 1
// https://adventofcode.com/2021/day/9
// input: day9/input.txt

const getNeighbors = (grid: number[][], x: number, y: number): number[] => {
  const neighbors = [];

  if (x > 0) {
    neighbors.push(grid[x - 1][y]);
  }
  if (x < grid.length - 1) {
    neighbors.push(grid[x + 1][y]);
  }
  if (y > 0) {
    neighbors.push(grid[x][y - 1]);
  }
  if (y < grid[0].length - 1) {
    neighbors.push(grid[x][y + 1]);
  }

  return neighbors;
};

const d9p1Input = (await Deno.readTextFile('day9/input.txt'))
  .split('\n')
  .filter((l) => !!l);

const grid = d9p1Input.map((line) =>
  line.split('').map((c) => parseInt(c, 10))
);

const lowPoints = [];

for (let y = 0; y < grid.length; y++) {
  for (let x = 0; x < grid[y].length; x++) {
    const numbersToCheck = getNeighbors(grid, y, x);

    if (numbersToCheck.every((n) => n > grid[y][x])) {
      lowPoints.push([y, x, grid[y][x]]);
    }
  }
}

const riskSum = lowPoints.reduce((sum, [_, __, val]) => sum + val + 1, 0);

console.log('\n');
console.log(
  `The sum of the risk at all low points in the heightmap is ${riskSum}.`
);
