# frozen_string_literal: true

# This file is generated by the setup script located in the utils folder in the repository root.
# Day 1
# https://adventofcode.com/2022/day/1
# input: day1/input.txt

# Solution just contains the input read in
module Solution
  INPUT = File.read('input.txt').split("\n").reject(&:empty?)
end

puts Solution::INPUT
