# frozen_string_literal: true

# This file is generated by the setup script located in the utils folder in the repository root.
# Day 1
# https://adventofcode.com/2022/day/1
# input: day1/input.txt

# Solution just contains the input read in
module Solution
  INPUT = File.read('input.txt').split("\n").reject(&:empty?)

  def self.find_file_calibration_value input_file
    input_file.reduce(0) do |sum, line|
      sum + find_line_calibration_value(line)
    end
  end

  def self.find_line_calibration_value line
    first_number_index = line.index(/\d{1}/)
    last_number_index = line.rindex(/\d{1}/)

    Integer("#{line[first_number_index]}#{line[last_number_index]}")
  end
end
