# frozen_string_literal: true

# This file is generated by the setup script located in the utils folder in the repository root.
# Run the tests using ruby solution_test.rb

require 'test/unit'

require_relative './solution'

# SanityTest just sanity tests the input
class SanityTest < Test::Unit::TestCase
  def test_input_not_nil
    assert_not_nil(Solution::INPUT)
  end
end
