// This file is generated by the create-files script in ../utils.
// Day 19 part 1
// https://adventofcode.com/2021/day/19
// input: day19/input.txt

type ScannerBeaconMap = Map<number, Array<{ x: number; y: number; z: number }>>;

const d19p1Input = (await Deno.readTextFile('day19/input.txt'))
  .split('\n\n')
  .filter((l) => !!l);

const scannerMap = d19p1Input.reduce((map, block) => {
  const lines = block.split('\n').filter((l) => !!l);
  const scannerIdLine = lines.shift()!.trim();
  const scannerNumber = /scanner\s(\d+)/.exec(scannerIdLine)![1];
  const beaconList = lines.map((l) => {
    const [x, y, z] = l.split(',').map(Number);
    return { x, y, z };
  });
  map.set(Number(scannerNumber), beaconList);
  return map;
}, new Map() as ScannerBeaconMap);

console.log(scannerMap);
