
// This file is generated by the create-files script in ../utils.
// Day 19 part 1
// https://adventofcode.com/2021/day/19
// input: day19/input.txt

const d19p1Input = (await Deno.readTextFile('day19/input.txt'))
  .split('\n')
  .filter((l) => !!l);
console.log(d19p1Input);