import Language from './Language.ts';

export default class JavascriptNode implements Language {
  public static language = ['javascript', 'js'];

  private extension = 'js';
  private solutionFilePath: string;

  constructor(private year: number, private day: number) {
    this.solutionFilePath = `./${this.year}/day${this.day}/solution.${this.extension}`;
  }

  public getSolutionRootPath(): string {
    return `./${this.year}/day${this.day}`;
  }
  public getSetupCommand(): string[] {
    return ['mkdir', '-p', this.getSolutionRootPath()];
  }
  public getFileNames(): {
    [key: string]: string;
    inputFile: string;
    solutionFile: string;
  } {
    return {
      inputFile: `./${this.year}/day${this.day}/input.txt`,
      solutionFile: this.solutionFilePath,
    };
  }
  public getFileContents(path: string): string {
    if (path === this.solutionFilePath) {
      return this.getSolutionFileContents();
    } else {
      throw new Error(`Unknown path: ${path}`);
    }
  }

  private getSolutionFileContents(): string {
    return `
// This file is generated by the setup script located in the utils folder in the repository root.
// Day ${this.day}
// https://adventofcode.com/${this.year}/day/${this.day}
// input: day${this.day}/input.txt

const d${this.day}Input = (await Deno.readTextFile('day${this.day}/input.txt'))
  .split('\\n')
  .filter((l) => !!l);

console.log(d${this.day}Input);
    `.trim();
  }
}
