// This file is generated by the create-files script in ../utils.
// Day 10 part 2
// https://adventofcode.com/2021/day/10#part2
// input: day10/input.txt

import {
  countBrackets,
  openingBrackets,
  generateClosingBracketString,
  scoreGeneratedBracketString,
} from './bracketUtils.ts';

const d10p2Input = (await Deno.readTextFile('day10/input.txt'))
  .split('\n')
  .filter((l) => !!l);

const incompleteLineScores = d10p2Input
  .map(countBrackets)
  .filter((bracketStack) =>
    bracketStack.every((c) => openingBrackets.includes(c))
  )
  .map((bracketStack) => generateClosingBracketString(bracketStack))
  .map(scoreGeneratedBracketString)
  .sort((a, b) => a - b);

console.log(incompleteLineScores[Math.floor(incompleteLineScores.length / 2)]);
