// This file is generated by the create-files script in ../utils.
// Day 10 part 1
// https://adventofcode.com/2021/day/10
// input: day10/input.txt

import {
  countBrackets,
  openingBrackets,
  scoreCorruptedLinesReducer,
} from './bracketUtils.ts';

const d10p1Input = (await Deno.readTextFile('day10/input.txt'))
  .split('\n')
  .filter((l) => !!l);

const corruptedLinesScore = d10p1Input
  .map(countBrackets)
  .filter(
    (bracketStack) => !bracketStack.every((c) => openingBrackets.includes(c))
  )
  .reduce(scoreCorruptedLinesReducer, 0);

console.log(corruptedLinesScore);
