// This file is generated by the setup script located in the utils folder in the repository root.
// Run the tests using npm test

const test = require('ava');

const { day1Input, part1, part2 } = require('./solution');

test('sanity test', (t) => {
  t.truthy(day1Input);
});

[
  { input: '>'.split(''), p1Expected: 2, p2Expected: 2 },
  { input: '^v'.split(''), p1Expected: 2, p2Expected: 3 },
  { input: '^>v<'.split(''), p1Expected: 4, p2Expected: 3 },
  { input: '^v^v^v^v^v'.split(''), p1Expected: 2, p2Expected: 11 },
  { input: day1Input, p1Expected: 2592, p2Expected: 2360 },
].forEach((tc) => {
  test(`[part1] Instructions ${
    tc.input.length > 10
      ? `${tc.input.slice(0, 10).join('')}...`
      : tc.input.join('')
  } deliver to ${tc.p1Expected} houses`, (t) => {
    t.is(part1(tc.input), tc.p1Expected);
  });

  test(`[part2] Instructions ${
    tc.input.length > 10
      ? `${tc.input.slice(0, 10).join('')}...`
      : tc.input.join('')
  } deliver to ${tc.p2Expected} houses`, (t) => {
    t.is(part2(tc.input), tc.p2Expected);
  });
});
