// This file is generated by the setup script located in the utils folder in the repository root.
// Day 3
// https://adventofcode.com/2015/day/3
// input: day3/input.txt

const { readFileSync } = require('fs');

const day1Input = readFileSync('input.txt', 'utf8')
  .split('\n')
  .filter((l) => !!l);

module.exports = { day1Input };
