// This file is generated by the setup script located in the utils folder in the repository root.
// Run the tests using npm test

const test = require('ava');

const { day1Input } = require('./solution');

test('sanity test', (t) => {
  t.truthy(day1Input);
});
