// This file is generated by the create-files script in ../utils.
// Day 14 part 2
// https://adventofcode.com/2021/day/14#part2
// input: day14/input.txt

import { getPairsFrom, checkAndInsertElement } from './utils.ts';

const generateNewPairs = (
  initialPair: string,
  insertionMap: Map<string, string>
) => {
  const [start, end] = initialPair.split('');
  const insertion = insertionMap.get(initialPair);
  return [start + insertion, insertion + end];
};

const [d14p2StartingChain, d14p2PairInsertions] = (
  await Deno.readTextFile('day14/input.txt')
)
  .split('\n\n')
  .filter((l) => !!l);
const startingChain = d14p2StartingChain.trim();
const pairInsertionMap = new Map<string, string>();

d14p2PairInsertions
  .split('\n')
  .filter((l) => !!l)
  .forEach((l) => {
    const [pair, insertion] = l.split(' -> ').map((s) => s.trim());
    pairInsertionMap.set(pair, insertion);
  });

const polymerMap = new Map<string, number>();
getPairsFrom(startingChain).forEach((p) => {
  if (!polymerMap.has(p)) {
    polymerMap.set(p, 0);
  }
  polymerMap.set(p, polymerMap.get(p)! + 1);
});
