// This file is generated by the create-files script in ../utils.
// Day 24 part 1
// https://adventofcode.com/2021/day/24
// input: day24/input.txt

class Instruction {
  public opcode: string;
  public args: [string, (string | number)?];

  constructor(input: string) {
    const [opcode, ...args] = input.split(' ');
    this.opcode = opcode;
    this.args = [args[0]];
    if (args[1]) {
      const numericArg = parseInt(args[1], 10);
      this.args[1] = isNaN(numericArg) ? args[1] : numericArg;
    }
  }
}

const d24p1Input = (await Deno.readTextFile('day24/input.txt'))
  .split('\n')
  .filter((l) => !!l);

const instructions = d24p1Input.map((i) => new Instruction(i));
console.log(instructions);
