// This file is generated by the setup script located in the utils folder in the repository root.
// Run the tests using npm test

const test = require('ava');

const { day1Input, part1, part2 } = require('./solution');

test('sanity test', (t) => {
  t.truthy(day1Input);
});

[
  { input: '()', output: 0 },
  { input: '(())', output: 0 },
  { input: '()()', output: 0 },
  { input: '(((', output: 3 },
  { input: '(()(()(', output: 3 },
  { input: '))(((((', output: 3 },
  { input: '())', output: -1 },
  { input: '))(', output: -1 },
  { input: ')))', output: -3 },
  { input: ')())())', output: -3 },
  { input: day1Input, output: 74 },
].forEach(({ input, output }) => {
  test(`[part1] ${
    input.length > 10 ? `${input.substr(0, 10)}...` : input
  } goes to floor ${output}`, (t) => {
    t.is(part1(input), output);
  });
});

[
  { input: ')', output: 1 },
  { input: '()())', output: 5 },
  { input: day1Input, output: 1795 },
].forEach(({ input, output }) => {
  test(`[part2] ${
    input.length > 10 ? `${input.substr(0, 10)}...` : input
  } goes into the basement at position ${output}`, (t) => {
    t.is(part2(input), output);
  });
});
