// This file is generated by the create-files script in ../utils.
// Day 5 part 2
// https://adventofcode.com/2021/day/5#part2
// input: day5/input.txt

import CartesianGrid from './CartesianGrid.ts';

const testInput = `
0,9 -> 5,9
8,0 -> 0,8
9,4 -> 3,4
2,2 -> 2,1
7,0 -> 7,4
6,4 -> 2,0
0,9 -> 2,9
3,4 -> 1,4
0,0 -> 8,8
5,5 -> 8,2
`;

const d5p2Input = (await Deno.readTextFile('day5/input.txt')) // testInput
  .split('\n')
  .filter((l) => !!l);
const grid = new CartesianGrid();

d5p2Input.forEach((line) => {
  const [p1, p2] = line.split('->').map((s) => s.trim());
  const [p1x, p1y] = p1.split(',').map((s) => parseInt(s, 10));
  const [p2x, p2y] = p2.split(',').map((s) => parseInt(s, 10));
  grid.plotLine(p1x, p1y, p2x, p2y, false);
});

console.log(grid.statistics);

const mostDangerousPoints = [...grid.entries()].filter(([_, v]) => v > 1);

console.log('\n');
console.log(
  `There are ${mostDangerousPoints.length} points that are not safe.`
);
