// This file is generated by the setup script located in the utils folder in the repository root.
// Run the tests using deno test --allow-read=input.txt solution.test.ts

import { assertExists } from "https://deno.land/std/testing/asserts.ts";

import { day6Input } from "./solution.ts";

Deno.test('sanity test', () => {
  assertExists(day6Input);
});
