// This file is generated by the setup script located in the utils folder in the repository root.
// Run the tests using deno test --allow-read=input.txt solution.test.ts

import {
  assertExists,
  assertEquals,
} from 'https://deno.land/std/testing/asserts.ts';

import { day6Input, parseCommand } from './solution.ts';

Deno.test('sanity test', () => {
  assertExists(day6Input);
});

[
  {
    input: 'turn on 0,0 through 999,999',
    output: {
      action: 'turn on',
      start: [0, 0],
      end: [999, 999],
    },
  },
  {
    input: 'toggle 0,0 through 999,0',
    output: {
      action: 'toggle',
      start: [0, 0],
      end: [999, 0],
    },
  },
].forEach((tc) => {
  Deno.test(`[parseCommand] parses ${tc.input} correctly`, () => {
    assertEquals(parseCommand(tc.input), tc.output);
  });
});
