// This file is generated by the setup script located in the utils folder in the repository root.
// Day 6
// https://adventofcode.com/2015/day/6
// input: day6/input.txt

const day6Input = (await Deno.readTextFile('input.txt'))
  .split('\n')
  .filter((l) => !!l);

const parseCommand = (command: string) => {
  const matches = command.match(/(.*) (\d+),(\d+) through (\d+),(\d+)/)!;
  return {
    action: matches[1],
    start: [
      Math.min(parseInt(matches[2]), parseInt(matches[4])),
      Math.min(parseInt(matches[3]), parseInt(matches[5])),
    ],
    end: [
      Math.max(parseInt(matches[2]), parseInt(matches[4])),
      Math.max(parseInt(matches[3]), parseInt(matches[5])),
    ],
  };
};

export { day6Input, parseCommand };
