// This file is generated by the setup script located in the utils folder in the repository root.
// Day 6
// https://adventofcode.com/2015/day/6
// input: day6/input.txt

const day6Input = (await Deno.readTextFile('input.txt'))
  .split('\n')
  .filter((l) => !!l);

export { day6Input };
