
// This file is generated by the create-files script in ../utils.
// Day 18 part 1
// https://adventofcode.com/2021/day/18
// input: day18/input.txt

const d18p1Input = (await Deno.readTextFile('day18/input.txt'))
  .split('\n')
  .filter((l) => !!l);
console.log(d18p1Input);