// This file is generated by the create-files script in ../utils.
// Day 6 part 1
// https://adventofcode.com/2021/day/6
// input: day6/input.txt

class LanternfishSchool {
  private fishies: number[];

  constructor(initialFishies: number[]) {
    this.fishies = initialFishies;
  }

  public simulate(days: number) {
    while (days > 0) {
      this.simulateOneDay();
      days--;
    }
  }

  public simulateOneDay() {
    const newFishiesToAdd: number[] = [];

    this.fishies = this.fishies
      .map((f) => {
        if (f === 0) {
          newFishiesToAdd.push(8);
          return 6;
        }
        return f - 1;
      })
      .concat(newFishiesToAdd);
  }

  public getCurrentState() {
    return this.fishies;
  }

  public get size() {
    return this.fishies.length;
  }
}

const d6p1Input = (await Deno.readTextFile('day6/input.txt'))
  .split(',')
  .filter((l) => !!l)
  .map((l) => parseInt(l, 10));

const school = new LanternfishSchool(d6p1Input);
const daysToSimulate = 80;
school.simulate(daysToSimulate);

console.log('\n');
console.log(
  `After ${daysToSimulate} days, the size of the school is ${school.size}`
);
