// This file is generated by the setup script located in the utils folder in the repository root.
// Run the tests using deno test --allow-read solution.test.ts

import {
  assertEquals,
  assertExists,
} from 'https://deno.land/std/testing/asserts.ts';

import { day2Input, part1 } from './solution.ts';

Deno.test('sanity test', () => {
  assertExists(day2Input);
});

[
  { input: [{ l: 2, w: 3, h: 4 }], output: 58 },
  { input: [{ l: 1, w: 1, h: 10 }], output: 43 },
  { input: day2Input, output: 1588178 },
].forEach((tc) => {
  Deno.test(
    `[part1] List of ${tc.input.length} presents require ${tc.output} sq feet of wrapping paper`,
    () => {
      assertEquals(part1(tc.input), tc.output);
    }
  );
});
