// This file is generated by the setup script located in the utils folder in the repository root.
// Day 2
// https://adventofcode.com/2015/day/2
// input: day2/input.txt

const day2Input = (await Deno.readTextFile('input.txt'))
  .split('\n')
  .filter((l) => !!l);

export { day2Input };
