// This file is generated by the setup script located in the utils folder in the repository root.
// Run the tests using deno test --allow-read solution.test.ts

import { assertExists } from "https://deno.land/std/testing/asserts.ts";

import { day2Input } from "./solution.ts";

Deno.test('sanity test', () => {
  assertExists(day2Input);
});
