
// This file is generated by the create-files script in ../utils.
// Day 25 part 1
// https://adventofcode.com/2021/day/25
// input: day25/input.txt

const d25p1Input = (await Deno.readTextFile('day25/input.txt'))
  .split('\n')
  .filter((l) => !!l);
console.log(d25p1Input);