// This file is generated by the create-files script in ../utils.
// Day 15 part 1
// https://adventofcode.com/2021/day/15
// input: day15/input.txt

const d15p1Input = (await Deno.readTextFile('day15/input.txt'))
  .split('\n')
  .filter((l) => !!l);

const chitonGrid = d15p1Input.map((row) =>
  row.split('').map((c) => parseInt(c, 10))
);

console.log(chitonGrid);
