// This file is generated by the setup script located in the utils folder in the repository root.
// Run the tests using go test *.go

package main

import "testing"

func TestDay4Part1(t *testing.T) {
	testCases := []struct {
		desc     string
		input    string
		expected int
	}{
		{
			desc:     "[part1] provided test case 1",
			input:    "abcdef",
			expected: 609043,
		},
		{
			desc:     "[part1] provided test case 2",
			input:    "pqrstuv",
			expected: 1048970,
		},
		{
			desc:     "[part1] test input",
			input:    "ckczppom",
			expected: 117946,
		},
	}
	for _, tC := range testCases {
		t.Run(tC.desc, func(t *testing.T) {
			output, err := Part1(tC.input)
			if err != nil {
				t.Fatal(err)
			} else if output != tC.expected {
				t.Fatalf("output: %d, expected: %d", output, tC.expected)
			}
		})
	}
}

func TestDay4Part2(t *testing.T) {
	testCases := []struct {
		desc     string
		input    string
		expected int
	}{
		{
			desc:     "[part2] provided test case 1",
			input:    "abcdef",
			expected: 609043,
		},
		{
			desc:     "[part2] provided test case 2",
			input:    "pqrstuv",
			expected: 1048970,
		},
		{
			desc:     "[part2] test input",
			input:    "ckczppom",
			expected: 117946,
		},
	}
	for _, tC := range testCases {
		t.Run(tC.desc, func(t *testing.T) {
			output, err := Part2(tC.input)
			if err != nil {
				t.Fatal(err)
			} else if output != tC.expected {
				t.Fatalf("output: %d, expected: %d", output, tC.expected)
			}
		})
	}
}
