// This file is generated by the setup script located in the utils folder in the repository root.
// Day 7
// https://adventofcode.com/2015/day/7
// input: day7/input.txt

mod utils;

fn main() {
    let lines = utils::lines_from_file("input.txt").expect("Could not load lines");

    for line in lines {
        println!("{:?}", line);
    }
}
