// This file is generated by the create-files script in ../utils.
// Day 16 part 2
// https://adventofcode.com/2021/day/16#part2
// input: day16/input.txt

import { RawNumericBuffer, parsePackets } from './packetProcessing.ts';

const d16p2Input = [
  'D2FE28',
  '38006F45291200',
  'EE00D40C823060',
  '8A004A801A8002F478',
  '620080001611562C8802118E34',
  'C0015000016115A2E0802F182340',
  'A0016C880162017C3686B18A3D4780',
  await Deno.readTextFile('day16/input.txt'),
].map((i) =>
  i
    .split('')
    .map((h) => parseInt(h, 16).toString(2).padStart(4, '0'))
    .join('')
);

const parsedPackets = d16p2Input
  .map((i) => new RawNumericBuffer(i))
  .map((b) => parsePackets(b));

console.dir(parsedPackets.map((p) => p.versionSum()));
