
// This file is generated by the create-files script in ../utils.
// Day 16 part 1
// https://adventofcode.com/2021/day/16
// input: day16/input.txt

const d16p1Input = (await Deno.readTextFile('day16/input.txt'))
  .split('\n')
  .filter((l) => !!l);
console.log(d16p1Input);