// This file is generated by the setup script located in the utils folder in the repository root.
// Day 2
// https://adventofcode.com/2023/day/2
// input: day2/input.txt

#[macro_use(lazy_static)]
extern crate lazy_static;

mod game_node;
mod utils;

fn main() {
    let lines = utils::lines_from_file("input.txt").expect("Could not load lines");

    for line in lines {
        println!("{:?}", line);
    }
}
