// This file is generated by the setup script located in the utils folder in the repository root.
// Run the tests using cargo test

use std::{
    fs::File,
    io::{BufRead, BufReader, Result},
    path::Path,
};

pub fn lines_from_file(filename: impl AsRef<Path>) -> Result<Vec<String>> {
    BufReader::new(File::open(filename)?).lines().collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_lines_from_file() {
        match lines_from_file("input.txt") {
            Ok(lines) => {
                assert_ne!(lines.len(), 0);
            }
            Err(e) => {
                panic!("{:?}", e);
            }
        }
    }
}
