// This file is generated by the create-files script in ../utils.
// Day 20 part 2
// https://adventofcode.com/2021/day/20#part2
// input: day20/input.txt

const d20p2Input = (await Deno.readTextFile('day20/input.txt'))
  .split('\n')
  .filter((l) => !!l);
console.log(d20p2Input);
