// This file is generated by the create-files script in ../utils.
// Day 20 part 1
// https://adventofcode.com/2021/day/20
// input: day20/input.txt

const getSquareOfPixels = <T>(
  grid: T[][],
  posx: number,
  posy: number,
  defaultValue: T
): T[] =>
  [
    grid[posy - 1]?.[posx - 1],
    grid[posy - 1]?.[posx],
    grid[posy - 1]?.[posx + 1],
    grid[posy]?.[posx - 1],
    grid[posy]?.[posx],
    grid[posy]?.[posx + 1],
    grid[posy + 1]?.[posx - 1],
    grid[posy + 1]?.[posx],
    grid[posy + 1]?.[posx + 1],
  ].map((v) => (v !== undefined ? v : defaultValue));

const defaultValue = '.';

const d20p1Input = (await Deno.readTextFile('day20/input.txt')).split('\n\n');

const imageProcessingMap = d20p1Input[0].split('');
const image = d20p1Input[1]
  .split('\n')
  .filter(Boolean)
  .map((l) => l.split(''));

console.log(getSquareOfPixels(image, 1, 1, defaultValue));
