// This file is generated by the create-files script in ../utils.
// Day 21 part 2
// https://adventofcode.com/2021/day/21#part2
// input: day21/input.txt

enum Players {
  P1 = 1,
  P2,
}

const d21p2Input = (await Deno.readTextFile('day21/input.txt'))
  .split('\n')
  .filter((l) => !!l);

const [p1Start, p2Start] = d21p2Input.map((l) => l.split(': ')[1].trim());

const p1 = { id: Players.P1, position: Number(p1Start), score: 0, wins: 0 };
const p2 = { id: Players.P2, position: Number(p2Start), score: 0, wins: 0 };
