
// This file is generated by the create-files script in ../utils.
// Day 23 part 2
// https://adventofcode.com/2021/day/23#part2
// input: day23/input.txt

const d23p2Input = (await Deno.readTextFile('day23/input.txt'))
  .split('\n')
  .filter((l) => !!l);
console.log(d23p2Input);