// This file is generated by the create-files script in ../utils.
// Day 23 part 2
// https://adventofcode.com/2021/day/23#part2
// input: day23/input.txt

/*
  Took a lot of time but I used https://amphipod.net/
  to work it out by hand for the most part. The undo feature
  is pretty 10/10.
*/
