// This file is generated by the create-files script in ../utils.
// Day 23 part 1
// https://adventofcode.com/2021/day/23
// input: day23/input.txt

/*
Okay, we're just going to solve this intuitively.

Energy requirements are
A - 1
B - 10
C - 100
D - 1000

#############
#...........#
###B#A#B#C###  Effort = 0
  #D#A#D#C#
  #########

#############
#AA.........#
###B# #B#C###  Effort = 10
  #D# #D#C#
  #########

#############
#AA.........#
###B#.#.#C###  Effort = 60
  #D#B#D#C#
  #########

#############
#AA.........#
###.#B#.#C###  Effort = 100
  #D#B#D#C#
  #########

#############
#AA.......C.#
###.#B#.#.###  Effort = 300
  #D#B#D#C#
  #########

#############
#AA...C...C.#
###.#B#.#.###  Effort = 800
  #D#B#D#.#
  #########

#############
#AA...C...C.#
###.#B#.#.###  Effort = 6800
  #D#B#.#D#
  #########

#############
#AA.........#
###.#B#C#.###  Effort = 7500
  #D#B#C#D#
  #########

#############
#AA.........#
###.#B#C#D###  Effort = 16500
  #.#B#C#D#
  #########

#############
#...........#
###A#B#C#D###  Effort = 16506
  #A#B#C#D#
  #########
*/
