// This file is generated by the create-files script in ../utils.
// Day 11 part 1
// https://adventofcode.com/2021/day/11
// input: day11/input.txt

import {
  Octopus,
  increaseEnergies,
  getReadyToFlashOctopii,
  flash,
  resetEnergies,
} from './faunaUtils.ts';

const d11p1Input = (await Deno.readTextFile('day11/input.txt'))
  .split('\n')
  .filter((l) => !!l);

const allOctopii = d11p1Input.map((l, y) =>
  l.split('').map((o, x) => new Octopus(x, y, parseInt(o, 10)))
);

const stepsToSimulate = 100;
let flashes = 0;

for (let s = 0; s < stepsToSimulate; s++) {
  increaseEnergies(allOctopii);
  const readyToFlash = getReadyToFlashOctopii(allOctopii);
  flashes += flash(allOctopii, readyToFlash).reduce((a, b) => a + b, 0);
  resetEnergies(allOctopii);
}

console.log('\n');
console.log(
  `There have been ${flashes} flashes after ${stepsToSimulate} steps.`
);
