// This file is generated by the create-files script in ../utils.
// Day 11 part 2
// https://adventofcode.com/2021/day/11#part2
// input: day11/input.txt

import {
  Octopus,
  increaseEnergies,
  getReadyToFlashOctopii,
  flash,
  resetEnergies,
} from './faunaUtils.ts';

const d11p2Input = (await Deno.readTextFile('day11/input.txt'))
  .split('\n')
  .filter((l) => !!l);

const allOctopii = d11p2Input.map((l, y) =>
  l.split('').map((o, x) => new Octopus(x, y, parseInt(o, 10)))
);

let stepFlashes = 0;
let step = 0;

while (stepFlashes !== 100) {
  increaseEnergies(allOctopii);
  const readyToFlash = getReadyToFlashOctopii(allOctopii);
  stepFlashes = flash(allOctopii, readyToFlash).reduce((a, b) => a + b, 0);
  step++;
  resetEnergies(allOctopii);
}

console.log('\n');
console.log(`It took ${step} steps to flash all ${stepFlashes} octopii.`);
